repo:
  public: gatsby-plugin-launchdarkly

template:
  name: npm

publications:
  - url: https://www.npmjs.com/package/gatsby-plugin-launchdarkly
    description: npm

documentation:
  githubPages: false